// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1719.TEST.commands;

//import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
//import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


import org.usfirst.frc1719.TEST.Robot;

/**
 *
 */
public class  UseDrive extends Command {
	private static final int LEFT_X = 0;
	private static final int LEFT_Y = 1;
	private static final int RIGHT_X = 4;
	
	private int i = 0;
	
	
	boolean driveType;
    public UseDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double ly = Robot.oi.getJoystick1().getRawAxis(LEFT_Y);
    	double lx = Robot.oi.getJoystick1().getRawAxis(LEFT_X);
    	double rx = Robot.oi.getJoystick1().getRawAxis(RIGHT_X);
    	
    	/* Paranoia -- div/0 */
    	if(ly == 0.0D) Robot.drive.moveMechanum(Math.sqrt((ly * ly) + (lx * lx)), Math.signum(lx) * Math.PI / 2, rx);
    	else Robot.drive.moveMechanum(Math.sqrt((ly * ly) + (lx * lx)), (ly < 0) ? (Math.PI - Math.atan(lx / ly)) : Math.atan(lx / ly), rx);
    	
    	//Print Statements

        System.out.println("Infrared Value: " + Robot.sensors.getIRSensorValue()); 
    	//System.out.println("Encoder1 Rate: " + Robot.sensors.getEncoderRate(1) + "Encoder2 Rate: " + Robot.sensors.getEncoderRate(2));
    	
    	
    	//System.out.println("Encoder1 Rate: " + encoder1Rate + "Encoder2 Rate: " + encoder2Rate);
    	
    	
    	
    	//System.out.println("Encoder1 Accuracy: " + encoder1Accuracy + " Encoder2 Accuracy: " + encoder2Accuracy);

        //System.out.println("Infrared Value: " + Robot.sensors.getIRSensorValue()); 
    	System.out.println("Encoder1 RPM: " + Robot.sensors.getEncoderRPM(1) + "  Infrared Value: " + Robot.sensors.getIRSensorValue());
    	/*
    	 */
    	System.out.println(Robot.sensors.getIRSensorValue());
    	
    	if (i++ % 0x40 == 0) System.out.println("Gyro angle: " + Robot.sensors.getGyro().getAngle());
    	if (i % 0x1000 == 0) {
    		System.out.println("Resetting gyro...");
    		Robot.sensors.getGyro().reset();
    		System.out.println("Done.");
    	}


    }
    
    
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
